In [15]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from bs4 import BeautifulSoup # web-scraping

In [ ]:
# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [28]:
import pandas as pd
modellingph2=pd.read_csv("D:/DPA/vehiclesModelling (1).csv")

In [29]:
modellingph2.drop(["age"],axis=1,inplace=True)
modellingph2.head()

,price,year,manufacturer,condition,cylinders,fuel,odometer,title_status,transmission,drive,type,paint_color,state,state_trans
0,17899,2012.0,volkswagen,excellent,4,gas,63500.0,clean,manual,4wd,hatchback,black,ut,west
1,13999,2009.0,ram,good,6,gas,120057.0,clean,automatic,4wd,pickup,silver,ut,west
2,34500,2017.0,ford,excellent,6,diesel,95484.0,clean,automatic,4wd,pickup,white,ut,west
3,14500,2007.0,gmc,excellent,6,gas,89340.0,clean,automatic,4wd,pickup,white,ut,west
4,12500,2013.0,ford,salvage,6,gas,226031.0,clean,automatic,4wd,pickup,white,ut,west

In [30]:
import requests
website_url = requests.get("https://en.wikipedia.org/wiki/List_of_U.S._states_by_GDP_per_capita").text
soup = BeautifulSoup(website_url,"lxml")

my_table = soup.find("table",{"class":"wikitable sortable"})
my_table
names=my_table.findAll('tr')
soup = BeautifulSoup(website_url,"html.parser")
rows = []
for tr in soup.select('tr'):
    rows.append([td.get_text(strip=True) for td in tr.select('th, td')])
    
rows_up=rows[:len(rows)-77]

gdp=pd.DataFrame(rows_up,columns=["Rank","State","2018","2017","2016","2015","2014","2013","2012","2011"])

gdp.drop(["Rank"],axis=1,inplace=True)
gdp.drop(gdp.index[[0,1,23]],inplace=True)
gdp["State"]=gdp["State"].str.lower()

gdp.columns=["US States","GDP2018","GDP2017","GDP2016","GDP2015","GDP2014","GDP2013","GDP2012","GDP2011"]
gdp.index=range(1,len(gdp)+1)

columns=["GDP2018","GDP2017","GDP2016","GDP2015","GDP2014","GDP2013","GDP2012","GDP2011"]

In [31]:
us_state_abbrev = {
    'alabama': 'AL',
    'alaska': 'AK',
    'american samoa': 'AS',
    'arizona': 'AZ',
    'arkansas': 'AR',
    'california': 'CA',
    'colorado': 'CO',
    'connecticut': 'CT',
    'delaware': 'DE',
    'district of columbia': 'DC',
    'florida': 'FL',
    'georgia': 'GA',
    'guam': 'GU',
    'hawaii': 'HI',
    'idaho': 'ID',
    'illinois': 'IL',
    'indiana': 'IN',
    'iowa': 'IA',
    'kansas': 'KS',
    'kentucky': 'KY',
    'louisiana': 'LA',
    'maine': 'ME',
    'maryland': 'MD',
    'massachusetts': 'MA',
    'michigan': 'MI',
    'minnesota': 'MN',
    'mississippi': 'MS',
    'missouri': 'MO',
    'montana': 'MT',
    'nebraska': 'NE',
    'nevada': 'NV',
    'new hampshire': 'NH',
    'new jersey': 'NJ',
    'new mexico': 'NM',
    'new york': 'NY',
    'north carolina': 'NC',
    'north dakota': 'ND',
    'northern mariana islands':'MP',
    'ohio': 'OH',
    'oklahoma': 'OK',
    'oregon': 'OR',
    'pennsylvania': 'PA',
    'puerto rico': 'PR',
    'rhode island': 'RI',
    'south carolina': 'SC',
    'south dakota': 'SD',
    'tennessee': 'TN',
    'texas': 'TX',
    'utah': 'UT',
    'vermont': 'VT',
    'virgin islands': 'VI',
    'virginia': 'VA',
    'washington': 'WA',
    'west virginia': 'WV',
    'wisconsin': 'WI',
    'wyoming': 'WY'
}

for index,row in gdp.iterrows():
    gdp.at[index,"US States"]=us_state_abbrev[row["US States"]]

gdp["US States"]=gdp["US States"].str.lower()
gdp.columns=["state","GDP2018","GDP2017","GDP2016","GDP2015","GDP2014","GDP2013","GDP2012","GDP2011"]

In [57]:
updatedsecondary=pd.merge(modellingph2,gdp,on="state")

In [62]:
updatedsecondary.drop(['state'],axis=1,inplace=True)

updatedsecondary.rename(columns={'state_trans':'state'},inplace=True)

In [64]:
updatedsecondary.head()

,price,year,manufacturer,condition,cylinders,fuel,odometer,title_status,transmission,drive,...,paint_color,state,GDP2018,GDP2017,GDP2016,GDP2015,GDP2014,GDP2013,GDP2012,GDP2011
0,17899,2012.0,volkswagen,excellent,4,gas,63500.0,clean,manual,4wd,...,black,west,"44,636","44,204","43,069","42,267","41,929","41,992","41,500","41,563"
1,13999,2009.0,ram,good,6,gas,120057.0,clean,automatic,4wd,...,silver,west,"44,636","44,204","43,069","42,267","41,929","41,992","41,500","41,563"
2,34500,2017.0,ford,excellent,6,diesel,95484.0,clean,automatic,4wd,...,white,west,"44,636","44,204","43,069","42,267","41,929","41,992","41,500","41,563"
3,14500,2007.0,gmc,excellent,6,gas,89340.0,clean,automatic,4wd,...,white,west,"44,636","44,204","43,069","42,267","41,929","41,992","41,500","41,563"
4,12500,2013.0,ford,salvage,6,gas,226031.0,clean,automatic,4wd,...,white,west,"44,636","44,204","43,069","42,267","41,929","41,992","41,500","41,563"

In [65]:
updatedsecondary.to_csv("vehiclesplusGDP.csv",index=False)